onlyBuiltDependencies:
  - auto-transition
  - better-sqlite3
  - electron
  - nano-git
  - core-js
  - esbuild

allowBuilds:
  auto-transition: true
  better-sqlite3: true
  electron: true
  nano-git: true
  core-js: true
  esbuild: true
